
export { default as Benefits } from './benefits/benefits'
export { default as Faq } from './faq/faq'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as NavItem } from './navbar/nav-item'
export { default as NavMobile } from './navbar/nav-mobile'
export { default as Navbar } from './navbar/navbar'
export { default as Contact } from './contact/contact'
export { default as Testimonials } from './testimonials/testimonials'